Repository markslide/markslide, pull requests merged in 2019-09, with the labels that each got.

#24 basic preview component
  src/components/previewer.tsx
  src/components/slide-preview.tsx
  src/components/slide.tsx
  src/pages/edit.page.tsx
Labels: feature

#27 fix fullscreen on safari
  src/pages/presentation.page.tsx
Labels: bug

#32 add markdown classnames
  src/components/slide.tsx
  src/utils/get-markdown-class-names.ts
Labels: feature

#34 Theme editing page
  package.json
  src/components/app-router.tsx
  src/components/box.ts
  src/components/color-picker.tsx
  src/components/color-scheme.tsx
  src/components/edit-page-header.tsx
  src/components/page-header.tsx
  src/components/slides-ratio-select.tsx
  src/components/theme-select-page-header.tsx
  src/pages/edit.page.tsx
  src/pages/theme-select.page.tsx
  src/utils/style-consts.ts
  yarn.lock
Labels: feature

#39 Feat/templates
  src/components/slide.tsx
  src/pages/presentation.page.tsx
  src/themes/_backgrounds/cover-img.svg
  src/themes/_backgrounds/page-img.svg
  src/themes/_dev/bgi.png
  src/themes/_dev/cover-img.png
  src/themes/_dev/img-1.png
  src/themes/_dev/logo.png
  src/themes/background.less
  src/themes/citrine/main.less
  src/themes/github/github.less
  src/themes/inline-svg.less.js
Labels: enhancement

#40 Feat/beautiful editor
  .gitignore
  src/components/editor.tsx
  src/components/md-editor.tsx
  src/utils/editor-style.ts
Labels: enhancement

#42 Refactor/md editor
  README.md
  package.json
  src/components/editor.tsx
  src/components/md-editor.tsx
  src/stores/slide.store.ts
  yarn.lock
Labels: enhancement

#43 fixed some bugs and create 5 colors
  src/components/slide.tsx
  src/themes/citrine/color-1.less
  src/themes/citrine/color-2.less
  src/themes/citrine/color-3.less
  src/themes/citrine/color-4.less
  src/themes/citrine/color-5.less
  src/themes/citrine/dotted-circle.svg
  src/themes/citrine/main.less
Labels: enhancement
