Repository markslide/markslide, pull requests merged in 2019-10, with the labels that each got.

#48 Feat/template/one dark
  src/themes/_code-hl/color-1.less
  src/themes/one-dark/index.less
Labels: enhancement

#49 add page number
  src/entries/index.tsx
  src/stores/theme.store.ts
  src/themes/citrine/elements.less
  src/themes/citrine/main.less
  src/themes/style.less
Labels: enhancement

#53 分离content和background
  src/classes/ratio.ts
  src/components/previewer.tsx
  src/components/scale.tsx
  src/components/slide-background.tsx
  src/components/slide-content.tsx
  src/components/slide-preview.tsx
  src/components/slide.tsx
  src/components/slides-ratio-select.tsx
  src/pages/presentation.page.tsx
  src/pages/theme-select.page.tsx
  src/stores/slide.store.ts
  src/stores/theme.store.ts
  src/themes/one-dark/index.less
  src/themes/style.less
  src/utils/film-size.ts
Labels: refactor

#55 增加theme选择器
  src/classes/theme.ts
  src/components/app-router.tsx
  src/components/edit-page-header.tsx
  src/components/global-style.ts
  src/components/modal.tsx
  src/components/slide/slide-preview.tsx
  src/components/slide/slide.tsx
  src/components/theme-container.tsx
  src/components/theme-modal.tsx
  src/components/theme-select-page-header.tsx
  src/entries/index.tsx
  src/pages/edit.page.tsx
  src/pages/presentation.page.tsx
  src/pages/theme-select.page.tsx
  src/stores/theme.store.ts
  src/utils/themes.ts
Labels: feature

#58 Minor fix for theme citrine
  src/components/theme-modal.tsx
  src/themes/citrine/main.less
  src/themes/style.less
Labels: bug

#59 control layer
  src/components/control-layer.tsx
  src/pages/presentation.page.tsx
Labels: feature

#60 Add icons for presentation mode
  src/assets/icon/arrow-left.svg
  src/assets/icon/arrow-right.svg
  src/assets/icon/exit.svg
  src/assets/icon/fullscreen.svg
Labels: enhancement

#61 Update README.md
  README.md
Labels: documentation

#62 Fix/themes/191016
  src/entries/index.tsx
  src/themes/citrine/parts/elements.less
  src/themes/one-dark/index.less
  src/themes/one-dark/parts/cover.less
  src/themes/one-dark/parts/elements.less
  src/themes/one-dark/parts/section.less
  src/themes/style.less
  src/themes/test/main.less
  src/themes/test/parts/cover.less
  src/themes/test/parts/elements.less
  src/themes/utils.less
  src/utils/themes.ts
Labels: bug

#64 refine styles
  src/themes/one-dark/parts/column.less
  src/themes/one-dark/parts/elements.less
  src/themes/one-dark/parts/section.less
  src/themes/style.less
  src/themes/utils.less
  src/utils/editor-style.ts
Labels: enhancement
